version: '3'
services:
  frontend:
    build:
      context: ./frontApp
    ports:
      - "4200:80"

  spring-boot-app:
    build:
      context: ./practica_Spring_Angular
    ports:
      - "8080:8080"